### ISSUE TITLE
deposit: All headers are red on error

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-deposit#193] opened 2022-05-04 12:08 UTC
Package version (if known): v9.0.0.dev14

## Describe the bug
When there is an error in the form, all headers change the color to red

## Steps to Reproduce
1. Go to deposit form
2. Fill in the required fields except for the files.
3. Save the draft
4. See all headers changed color to red

## Expected behavior
Only the header that contain the field with the error should change color to red.

## Screenshots (if applicable)
![screencapture-127-0-0-1-5000-uploads-vq6f1-twc35-2022-05-04-14_03_56](https://user-images.githubusercontent.com/15194802/166678086-143f4db3-02b4-4dec-8a7c-c579c94487aa.png)

**Comment by jennur** [comment] 2022-05-05 07:08
There is a proposed solution in this task  https://github.com/inveniosoftware/react-invenio-deposit/issues/471

**Comment by ppanero** [comment] 2022-05-10 09:09
Solution seems to have been merged and cannot reproduce... closing :)

P.S. dont bring back the dead ;) (invenio-deposit != react-invenio-deposit) hahahaha

**Closed by ppanero** 2022-05-10 09:09 UTC
